In [1]:
import Ipynb_importer
from a_basic_quant import *
from b_model import *
from c_train_and_test import *
from d_post_training_quantize import *

importing Jupyter notebook from a_basic_quant.ipynb
importing Jupyter notebook from b_model.ipynb
importing Jupyter notebook from c_train_and_test.ipynb
importing Jupyter notebook from d_post_training_quantize.ipynb


## 1、理解量化过程·教程
### 1.1 获得一个输入 torch.tensor

In [2]:
x = torch.randn(2,3) *100
x

tensor([[  37.7100, -247.2650,  195.9890],
        [-164.9726,   30.3538,   20.2909]])

### 1.2 获得 x 的最大值和最小值，确定上下限

In [3]:
max_val = x.max()
min_val = x.min()
print(f"max_val: {max_val} \nmin_val:{min_val}")

max_val: 195.989013671875 
min_val:-247.26495361328125


### 1.3 计算缩放因子 scare, 零点 zero_point

In [4]:
scale, zero_point = calcu_scale_and_zeropoint(min_val, max_val)
print(f"scale: {scale} \nzero_point: {zero_point}")

scale: 1.7382508516311646 
zero_point: 142.0


### 1.4 进行量化

In [5]:
q_x = quantize_tensor(x, scale, zero_point)
q_x

tensor([[163.6942,   0.0000, 254.7507],
        [ 47.0928, 159.4622, 153.6731]])

### 1.5 反量化

In [6]:
x_q_x = dequantize_tensor(q_x, scale, zero_point)

print(f"原始值：\n{x} \n量化反量化：\n{x_q_x}")

原始值：
tensor([[  37.7100, -247.2650,  195.9890],
        [-164.9726,   30.3538,   20.2909]]) 
量化反量化：
tensor([[  37.7100, -246.8316,  195.9890],
        [-164.9726,   30.3538,   20.2908]])


## 2、理解卷积中量化参与的过程

### 2.1 定义一个卷积

In [7]:
conv = torch.nn.Conv2d(1, 40, 3, 1)

### 2.2 定义输入 a 并且输出指定范围数据

In [8]:
a = torch.randn((64, 1, 28, 28))
a[0][0][0][:5]

tensor([ 2.0351, -1.0917, -1.2265,  1.2006,  0.4202])

### 2.3 卷积运算并且输出指定范围数据

In [9]:
a_out = conv(a)
a_out[0][0][0][:5]

tensor([0.1122, 0.7790, 0.5075, 0.2908, 0.4184], grad_fn=<SliceBackward>)

### 2.4 定义量化卷积层

In [10]:
qconv1 = QConv2d(conv, has_qin=True, has_qout=True, num_bits=8)

### 2.5 计算S 和 z，进行中间参数的量化，并保存

In [11]:
y = qconv1(a)
qconv1.freeze()

### 2.6 量化输入

In [20]:
# 量化输入
qa = qconv1.q_in.quantize_tensor(a).int().float()
print(f"量化输入，展示部分数据：{qa[0][0][0][:5]}")

# 反量化输入
# 这部分没必要，只是为了给你们展示看效果
qaa = qconv1.q_in.dequantize_tensor(qa)
print(f"\n反量化输入，展示部分数据：\n\n{qaa[0][0][0][:5]}\n")
print(f"原始数据对比：\n\n{a[0][0][0][:5]}")

量化输入，展示部分数据：tensor([196.,  97.,  93., 170., 145.])

反量化输入，展示部分数据：

tensor([ 2.0197, -1.1045, -1.2308,  1.1992,  0.4103])

原始数据对比：

tensor([ 2.0351, -1.0917, -1.2265,  1.2006,  0.4202])


### 2.7 使用量化输入进行推理

In [21]:
qa_out = qconv1.quantize_inference(qa)
print(f"推理输出，展示部分数据：{qa_out[0][0][0][:5]}")

qaa_out = qconv1.q_out.dequantize_tensor(qa_out)
print(f"\n反量化推理输出，展示部分数据：\n\n{qaa_out[0][0][0][:5]}\n")
print(f"原始推理结果对比：\n\n{a_out[0][0][0][:5]}")

推理输出，展示部分数据：tensor([137., 163., 152., 144., 149.], grad_fn=<SliceBackward>)

反量化推理输出，展示部分数据：

tensor([0.1271, 0.7880, 0.5084, 0.3050, 0.4321], grad_fn=<SliceBackward>)

原始推理结果对比：

tensor([0.1122, 0.7790, 0.5075, 0.2908, 0.4184], grad_fn=<SliceBackward>)


## 3、无法量化的缘故·教程

### 3.1 定义卷积

In [22]:
conv = torch.nn.Conv2d(1, 40, 3, 1)

### 3.2 定义输入并查看类型

In [23]:
a = torch.randn((64, 1, 28, 28))

print(f"shape: {a.shape} \ndtype: {a.dtype}")

shape: torch.Size([64, 1, 28, 28]) 
dtype: torch.float32


### 3.3 卷积运算（正常输出）

In [24]:
a_out = conv(a)

print(f"shape: {a_out.shape} \ndtype: {a_out.dtype}")

shape: torch.Size([64, 40, 26, 26]) 
dtype: torch.float32


### 3.4 改变输入类型

In [25]:
b = a.to(torch.uint8)

b.dtype

torch.uint8

### 3.5 卷积运算（错误输出）

In [26]:
b_out = conv(b)

RuntimeError: expected scalar type Byte but found Float

### 3.6 pytorch 目前无法量化的缘故（猜测）
- https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html
- https://www.tensorflow.org/api_docs/python/tf/nn/conv2d#args

for pytorch:
> This module supports TensorFloat32.

for tensorflow:
> A Tensor. Must be one of the following types: half, bfloat16, float32, float64.