In [1]:
import Ipynb_importer
from a_basic_quant import *
from b_model import *
from c_train_and_test import *
from d_post_training_quantize import *

importing Jupyter notebook from a_basic_quant.ipynb
importing Jupyter notebook from b_model.ipynb
importing Jupyter notebook from c_train_and_test.ipynb
importing Jupyter notebook from d_post_training_quantize.ipynb


## 1、理解量化过程·教程
### 1.1 获得一个输入 torch.tensor

In [2]:
x = torch.randn(2,3) *100
x

tensor([[   9.2214,   44.6691,  -28.8391],
        [-173.1100,   36.1256,  159.3336]])

### 1.2 获得 x 的最大值和最小值，确定上下限

In [3]:
max_val = x.max()
min_val = x.min()
print(f"max_val: {max_val} \nmin_val:{min_val}")

max_val: 159.3336181640625 
min_val:-173.10995483398438


### 1.3 计算缩放因子 scare, 零点 zero_point

In [4]:
scale, zero_point = calcu_scale_and_zeropoint(min_val, max_val)
print(f"scale: {scale} \nzero_point: {zero_point}")

scale: 1.30370032787323 
zero_point: 132.0


### 1.4 进行量化

In [5]:
q_x = quantize_tensor(x, scale, zero_point)
q_x

tensor([[139, 166, 109],
        [  0, 159, 254]], dtype=torch.uint8)

### 1.5 反量化

In [9]:
x_q_x = dequantize_tensor(q_x, scale, zero_point)

print(f"原始值：\n{x} \n量化反量化：\n{x_q_x}")

原始值：
tensor([[   9.2214,   44.6691,  -28.8391],
        [-173.1100,   36.1256,  159.3336]]) 
量化反量化：
tensor([[   9.1259,   44.3258,  -29.9851],
        [-172.0884,   35.1999,  159.0514]])
