In [2]:
import Ipynb_importer
from a_basic_quant import *
from b_model import *
from c_train_and_test import *
from d_post_training_quantize import *

importing Jupyter notebook from a_basic_quant.ipynb
importing Jupyter notebook from b_model.ipynb
importing Jupyter notebook from c_train_and_test.ipynb
importing Jupyter notebook from d_post_training_quantize.ipynb


## 1、理解量化过程·教程
### 1.1 获得一个输入 torch.tensor

In [3]:
x = torch.randn(2,3) *100
x

tensor([[-40.3169, -50.4716,  39.6022],
        [ 74.3491, -97.0853,  78.7182]])

### 1.2 获得 x 的最大值和最小值，确定上下限

In [4]:
max_val = x.max()
min_val = x.min()
print(f"max_val: {max_val} \nmin_val:{min_val}")

max_val: 78.71824645996094 
min_val:-97.08525848388672


### 1.3 计算缩放因子 scare, 零点 zero_point

In [5]:
scale, zero_point = calcu_scale_and_zeropoint(min_val, max_val)
print(f"scale: {scale} \nzero_point: {zero_point}")

scale: 0.6894254684448242 
zero_point: 140.0


### 1.4 进行量化

In [6]:
q_x = quantize_tensor(x, scale, zero_point).int()
q_x

tensor([[ 81,  66, 197],
        [247,   0, 254]], dtype=torch.int32)

### 1.5 反量化

In [7]:
x_q_x = dequantize_tensor(q_x, scale, zero_point)

print(f"原始值：\n{x} \n量化反量化：\n{x_q_x}")

原始值：
tensor([[-40.3169, -50.4716,  39.6022],
        [ 74.3491, -97.0853,  78.7182]]) 
量化反量化：
tensor([[-40.6761, -51.0175,  39.2973],
        [ 73.7685, -96.5196,  78.5945]])
